### PR TITLE
Change Turbo Stream media type

### PR DESCRIPTION
**Pull request by dunglas**
Follows hotwired/turbo#91.

### CODE REVIEW

**Comment by dunglas** [comment]
Updated to use the media type introduced in hotwired/turbo#93 (cc @sstephenson)

**Comment by Intrepidd** [comment]
👍  turbo beta 3 got released today so we need this for it to work properly on rails

**Comment by dixpac** [comment]
I can confirm that this is an issue I'm seeing this morning. Altho, I'm not sure wether https://github.com/hotwired/turbo-rails/blob/main/app/assets/javascripts/turbo.js requires any changes also

**Comment by Intrepidd** [comment]
Thanks @dhh 🙏 

Could we get a release though, AFAICS latest turbo-rails released version does not work properly with latest turbo beta. Thanks !

**Comment by dhh** [comment]
https://rubygems.org/gems/turbo-rails/versions/0.5.4 includes this fix. If you've found a bug with that, do open an issue on how to reproduce 👍

**Comment by Intrepidd** [comment]
My bad all is well on the turbo-rails side :+1:

**Pull request merged**
