### PR TITLE
Alter Action Cable Element to be morph-compatible

### PR DESCRIPTION
**Pull request by seanpdoyle**
Closes [#638][]

Recent changes to integrate with morphing have altered the mental model for some Turbo custom elements, including the
`<turbo-cable-stream-source>` element.

Custom Elements' `connectedCallback()` and `disconnectedCallback()` (along with Stimulus' `connect()` and `disconnect()`) improved upon invoking code immediately, or listening for `DOMContentLoaded` events.

There are similar improvements to be made to integrate with morphing. First, [observe attribute changes][] by declaring their own `static observedAttributes` properties along with
`attributeChangedCallback(name, oldValue, newValue)` callbacks. Those callbacks execute the same initialization code as their current `connectedCallback()` and `disconnectedCallback()` methods.

That'll help resolve this issue. In addition to those changes, it's important to emphasize this pattern for consumer applications moving forward. JavaScript code (whether Stimulus controller or otherwise) should be implemented in a way that' resilient to both asynchronous connection and disconnection *as well as* asynchronous modification of attributes.

[#638]: https://github.com/hotwired/turbo-rails/issues/638
[observe attribute changes]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Components/Using_custom_elements#responding_to_attribute_changes

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@jorgemanrubia @brunoprietog are either of you able to review these changes?

**Comment by Michoels** [comment]
This would be great!
Are there any plans to merge it?

**Review by jorgemanrubia — APPROVED** [review]
👏

**Comment by jorgemanrubia** [comment]
@seanpdoyle could you please solve the conflicts, I'll merge 🙏

**Pull request merged**
