### PR TITLE
Undefine check for custom element 'turbo-cable-stream-source'.  

### PR DESCRIPTION
**Pull request by riffdr**
Issue reported in https://github.com/hotwired/turbo-rails/issues/409

This

`
customElements.define("turbo-cable-stream-source", TurboCableStreamSourceElement);
`
Has been wrapped within an undefined check like the rest of the turbo custom elements. It randomly throws errors on the client that are being reported by Sentry in severa Rails applications. 

if (customElements.get("turbo-frame") === undefined) {
  customElements.define("turbo-frame", FrameElement);
}

if (customElements.get("turbo-stream") === undefined) {
  customElements.define("turbo-stream", StreamElement);
}

if (customElements.get("turbo-stream-source") === undefined) {
  customElements.define("turbo-stream-source", StreamSourceElement);
}

### CODE REVIEW

**Review by seanpdoyle — APPROVED** [review]

**Review by marcoroth — APPROVED** [review]
This looks also good to me! 👍🏼

**Comment by riffdr** [comment]
Thanks for the prompt response, any chance of merging this?

**Comment by riffdr** [comment]
Any first-time contributor available to approve this so that I can be released?

**Comment by riffdr** [comment]
Hi, i see the pipeline failed, what shoud I do https://github.com/hotwired/turbo-rails/actions/runs/3656035938/jobs/6260148576 ? The changes don't seem to related to the failing test

**Comment by kevinmcconnell** [comment]
@riffdr yes, it looks like a bit of test flakiness unrelated to your changes. I've re-run it for you.

**Comment by riffdr** [comment]
Thx for triggering the pipeline, looks like we have a green light, could you merge this onto master?

**Comment by riffdr** [comment]
Good morning and happy new year!

Could I please ask someone with write access to merge the request, thank you!

**Comment by kevinmcconnell** [comment]
@riffdr I can help with merging this. (And sorry for the slow reply to your last message -- I was out for the holidays).

The built assets need to be included in the changeset. Could you do a `yarn build` and add the updated files to your change? Thanks!

**Comment by riffdr** [comment]
Howdy Kevin, thx for your reply, I have just pushed the updated to the bundled js files.

**Comment by kevinmcconnell** [comment]
@riffdr thanks, that's it merged now.

**Comment by riffdr** [comment]
Howdy Kevin, thx a bunch

**Comment by riffdr** [comment]
hopefully, y'all can do a release soon.

**Pull request merged**
