### PR TITLE
remove unused morph tag builder

### PR DESCRIPTION
**Pull request by omarluq**
left over code from initial morph implementation

### CODE REVIEW

**Review by seanpdoyle — APPROVED** [review]
Thank you! Are there test examples or any other mention?

**Comment by omarluq** [comment]
> Thank you! Are there test examples or any other mention?

NP, no other references to this 👍🏼

**Comment by dhh** [comment]
cc @jorgemanrubia

**Comment by AlexKovynev** [comment]
anyway it is not enough need to fix this also https://github.com/hotwired/turbo-rails/issues/639

**Comment by jorgemanrubia** [comment]
Thanks @omarluq.

@AlexKovynev see my reply [here](https://github.com/hotwired/turbo-rails/issues/639#ref-pullrequest-2441245152).

**Pull request merged**
