### PR TITLE
Problem: inability to pass additional parameters to stream channels

### PR DESCRIPTION
**Pull request by yrashk**
Recently, an ability to customize channel has been added (https://github.com/hotwired/turbo-rails/pull/264).

However, it's still quite rigid as we can't pass any contextual information
from the client side. This can be very useful when, for example, there's a need
to indicate state of the page for the initial burst of messages upon
subscription.

Solution: allow passing additional parameters through `data-` attributes

This integrates nicely with `turbo_stream_from` helper which will be able
to process `data: {...}` attributes to pass them to the custom element.

`turbo-cable-stream-source` implementation has been updated to take these
dataset attributes into account and pass them along upon subscription.

### CODE REVIEW

**Comment by yrashk** [comment]
`CI / Tests (Ruby 3.0, Rails main) (pull_request)` failure might be a spurious browser waiting issue. The rest of the test runs succeeded.

**Comment by yrashk** [comment]
@dhh David, do you think this PR is of interest to the project?

**Comment by yrashk** [comment]
Anybody?

**Comment by dhh** [comment]
I don't have time to look at this at the moment. Feel free to run with this as a fork for now to serve your needs 👍

**Comment by yrashk** [comment]
I know I can use my fork. Is there anything I can do to reduce the chance of divergence? I prefer to avoid having forks where I can.

Can I be of any help to maintain the project?

As for the change in this PR. It may appear large, but it is primarily due to tests. The essential part is just this:

```diff
--- a/app/javascript/turbo/cable_stream_source_element.js
+++ b/app/javascript/turbo/cable_stream_source_element.js
@@ -1,5 +1,6 @@
 import { connectStreamSource, disconnectStreamSource } from "@hotwired/turbo"
 import { subscribeTo } from "./cable"
+import snakeize from "./snakeize"
 
 class TurboCableStreamSourceElement extends HTMLElement {
   async connectedCallback() {
@@ -20,7 +21,7 @@ class TurboCableStreamSourceElement extends HTMLElement {
   get channel() {
     const channel = this.getAttribute("channel")
     const signed_stream_name = this.getAttribute("signed-stream-name")
-    return { channel, signed_stream_name }
+    return { channel, signed_stream_name, ...snakeize({ ...this.dataset }) }
   }
 }
```

which is, arguably, a one-liner :)

**Comment by yrashk** [comment]
I've rebased this PR off the latest `main`. 

As for CI, I am not sure what's going on just yet, as the tests specified in `.github/worksflows/ci.yml` pass consistently with Ruby 3.0.2 locally:

```
$ bin/rails db:test:prepare
   bin/test test/**/*_test.rb
Installing Ruby dependencies
Installing JavaScript dependencies
Building JavaScript

app/javascript/turbo/index.js → app/assets/javascripts/turbo.js...
created app/assets/javascripts/turbo.js in 316ms

app/javascript/turbo/index.js → app/assets/javascripts/turbo.min.js...
created app/assets/javascripts/turbo.min.js in 477ms
Migrating test database
Run options: --seed 18459

# Running:

...2021-11-22 15:50:06 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
..................................................................

Finished in 2.356788s, 29.2771 runs/s, 53.4626 assertions/s.
69 runs, 126 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by yrashk** [comment]
@dhh do you think you'll be interested to try and add this (as I previously indicated) near-one-liner to Turbo-Rails after all or are you still busy to have a chance to review it? Thanks!

**Comment by yrashk** [comment]
Replaced with #308 308

**Pull request closed without merging**
