### PR TITLE
Revise how to disable eager loading app/channels

### LINKED ISSUE #512: Can't load turbo-rails without Action Cable starting in Rails 7.1.2
I'm not sure whether to report this bug here, or in Rails. Let me know if I should move it.

With today's release of Rails 7.1.2, it is no longer possible to use turbo-rails without Action Cable. I get the following error when eager loading is enabled:

```
NameError: uninitialized constant ActionCable (NameError)

class Turbo::StreamsChannel < ActionCable::Channel::Base
                                                  ^^^^^^
Did you mean?  Rational
/Users/mbrictson/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.5.0/app/channels/turbo/streams_channel.rb:34:in `<main>'
```

This check in the turbo-rails engine is supposed to automatically remove `app/channels` from the eager-load paths when Action Cable is not present:

https://github.com/hotwired/turbo-rails/blob/e44b6a98a77a0a2cc927f986a67517d73c4c9246/lib/turbo/engine.rb#L18-L20

However, starting with Rails 7.1.2, this technique apparently no longer works.

There were changes in Rails 7.1.2 regarding auto/eager loading of paths in engines (see https://github.com/rails/rails/pull/49636), so this could be a new bug Rails, or it could mean that turbo-rails needs to be changed to accommodate the new behavior.

_Edit: I confirmed that rolling back https://github.com/rails/rails/pull/49636 fixes the problem._

### PR DESCRIPTION
**Pull request by fxn**
(This is the same as #513, which I closed by accident.)

Fixes #512.

### CODE REVIEW

**Comment by dorianmariecom** [comment]
Thanks @dhh <3

**Comment by dorianmariecom** [comment]
@dhh Can you release a new version? That would be awesome

**Comment by t27duck** [comment]
Until a new version is released, this is the workaround I've been using that seems to work out well enough...

`config/application.rb`:

```ruby
require_relative "boot"

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
...
# require "action_cable/engine"
...

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

# Hack as turbo-rails loads the constant from the eager load paths.
# Remove once a new version is released.
class Turbo::StreamsChannel; end unless defined?(ActionCable)
```

**Comment by bruno-** [comment]
@afcapel any chance you can release a new gem version with this fix? 🙏

This is currently breaking my app in production (I have to resort to workarounds) because I'm using [mission_control-jobs](https://github.com/rails/mission_control-jobs) which is using turbo.

Many thanks

**Comment by AxelTheGerman** [comment]
Would also appreciate a new release that includes this fix. That should also solve #587 - I was just looking into fixing that and then found the code that already fixed it is there and merged but not released.

Thank you!

**Pull request merged**
